apiVersion: mdai.mdai.ai/v1
kind: MdaiHub
metadata:
  labels:
    app.kubernetes.io/name: mdai-operator
    app.kubernetes.io/managed-by: kustomize
  name: mdaihub-sample
spec:
  variables:
  # storageKey is how this variable will be referenced elsewhere in MDAI configs. Must be unique among configured variables.
    - storageKey: service_list
    # defaultValue is optional. It is the value that the variable is initialized with. It must be the same data type as specified in the `type` property.
      defaultValue: "n/a"
      # with clauses define how the variable is implemented in the k8s configMap
      with:
      # exportedVariableName is name provided for the environment variable version of the immediate parent variable. Must be unique among all environment variables.
        - exportedVariableName: "SERVICE_LIST_REGEX"
        # transformer is a programmatic transformation applied to the runtime value of the variable before setting the value in the k8s configMap
          transformer:
          # join the values of the variable into a single string
            join:
            # delimiter insert this delimiter string between values as they're joined
              delimiter: "|"
        - exportedVariableName: "SERVICE_LIST_CSV"
          transformer:
            join:
              delimiter: ","
      # below properties are optional
      type: set
      storageType: "mdai-valkey"
    - storageKey: team_list
      defaultValue: "n/a"
      with:
        - exportedVariableName: "TEAM_LIST_REGEX"
          transformer:
            join:
              delimiter: "|"
        - exportedVariableName: "TEAM_LIST_CSV"
          transformer:
            join:
              delimiter: ","
      # below properties are optional
      type: set
      storageType: "mdai-valkey"

  evaluations:
  # name required. must be unique across evaluations
    - name: top_talkers
    # type required. only one type supported for 0.6.0
      type: mdai/prometheus_alert
      # expr a valid PromQL query expression
      expr: 'increase(bytes_received_by_service_total{service_name!=""}[1h]) > 5*1024*1024'
      # severity alert severity
      severity: warning
      # onStatus Prometheus alerts will indicate a status of `firing` or `resolved`. An action may be configured for one or both events, but one must be configured for at least one.
      onStatus:
      # firing the status indicated when the conditions of the expr and for fields are met.
        firing:
        # variableUpdate the type of action to be performed.
          variableUpdate:
          # variableRef the storageKey of the variable to be updated.
            variableRef: service_list
            # operation the operation that will update the variable
            operation: mdai/add_element
        resolved:
          variableUpdate:
            variableRef: service_list
            operation: mdai/remove_element
      # Optional below here
      # for condition described by the expr must be true for this long before the alert fill fire
      for: 1m
      # keep_firing_for once the alert is sent with a status of `firing`, it will persist for this long
      keep_firing_for: 10m
      # relevantLabels names of fields attached to the alert whose values will be provided to the configured actions
      # for example, in this configured evaluation, the `expr` will be true on a per `service_name` basis, so indicating `service_name` in `relevantLabels` will ensure that when the `expr` is true for a given `service_name` that value will be added to the `service_list` runtime value
      relevantLabels:
        - "service_name"
    - name: top_listeners
      type: mdai/prometheus_alert
      expr: 'increase(bytes_sent_by_service_total{service_name!=""}[1h]) > 10*1024*1024'
      severity: warning
      for: 15m
      keep_firing_for: 10m
    - name: top_team_talkers
      type: mdai/prometheus_alert
      expr: 'increase(bytes_received_by_team_region_total{team!=""}[1h]) > 10*1024*1024'
      severity: warning
      for: 3m
      keep_firing_for: 10m
      relevantLabels:
        - "team"
      onStatus:
        firing:
          variableUpdate:
            variableRef: team_list
            operation: mdai/add_element
        resolved:
          variableUpdate:
            variableRef: team_list
            operation: mdai/remove_element

  observers:
    - name: watcher1
      labelResourceAttributes:
        - service.name
      countMetricName: items_received_by_service_total
      bytesMetricName: bytes_received_by_service_total
      filter:
        error_mode: ignore
        logs:
          log_record:
            - 'resource.attributes["watcher_direction"] != "received"'
    - name: watcher2
      labelResourceAttributes:
        - service.name
      countMetricName: items_sent_by_service_total
      bytesMetricName: bytes_sent_by_service_total
      filter:
        error_mode: ignore
        logs:
          log_record:
            - 'resource.attributes["watcher_direction"] != "exported"'
    - name: team-region-received
      labelResourceAttributes:
        - region
        - team
      countMetricName: items_sent_by_team_region_total
      bytesMetricName: bytes_sent_by_team_region_total
      filter:
        error_mode: ignore
        logs:
          log_record:
            - 'resource.attributes["watcher_direction"] != "exported"'
