{
 "title": "Services I/O",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Totals for I/O Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MDAI Total Services Monitored",
   "type": "stat",
   "description": "Unique services MDAI is capturing logs for",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(service_name) (rate(mdai_logs_received_total[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {},
    {}
   ]
  },
  {
   "title": "I/O Logs",
   "type": "barchart",
   "description": "The ingress and egress of logs sent through MDAI",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(sum by(service_name) (increase(mdai_logs_received_total[$__rate_interval:])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(sum by(service_name) (increase(mdai_logs_sent_total[$__rate_interval:])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Percentage Difference I/O",
   "type": "gauge",
   "description": "Difference between I/O logs on average over selected timeframe.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(increase(mdai_logs_received_total[$__rate_interval:])) - sum(increase(mdai_logs_sent_total[$__rate_interval:]))",
     "legendFormat": "__auto"
    },
    { "expression": "$A * 100", "type": "math" }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "MDAI I/O by service_name",
   "type": "table",
   "description": "Logs received by MDAI and sent from MDAI in total and bytes",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by(service_name) (increase(mdai_logs_received_total[$__rate_interval:]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(service_name) (increase(mdai_log_bytes_received_total[$__rate_interval:]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(service_name) (increase(mdai_logs_sent_total[$__rate_interval:]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(service_name) (increase(mdai_log_bytes_sent_total[$__rate_interval:]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Talkers I/O Logs Totals",
   "type": "timeseries",
   "description": "Top talkers received through MDAI and reduction",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by(service_name) (increase(mdai_logs_sent_total[$__rate_interval:])) > 50",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(service_name) (increase(mdai_logs_received_total[$__rate_interval:])) > 50",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Active Filters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  { "title": "Active Filters", "type": "alertlist", "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 } }
 ]
}